### ISSUE TITLE
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE when working with on premise SSL endpoint

### ISSUE THREAD

**Issue by inovakov** [apigee/apigeetool-node#6]
We have our own instance of Apigee and when trying to use our SSL endpoint (base URL) with apigeetool, I get:

```
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
    at SecurePair.<anonymous> (tls.js:1380:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:979:10)
    at CleartextStream.read [as _read] (tls.js:471:13)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
```

There should be a way, how to specify the certificate used for validation of the endpoint certificate.

Any ideas how this can be done?

Thanks.

**Comment by tmarrs** [comment]
How about implementing both solutions (PEM certificate and also bypass completely)?

**Comment by prabhatjha** [comment]
We will get this done in next release.

**Comment by ivan-novakov** [comment]
I think, this problem has been resolved in #7 . At least it works for me :).

**Comment by tmarrs** [comment]
I tried the `insecure` option and it didn't solve https://github.com/apigee/apigeetool-node/issues/33
